repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: my-postgresql
    chart: bitnami/postgresql
    version: 15.5.0
    installed: false
    values:
      - auth:
          username: cruduser
          password: password
          database: cruddb

  - name: backendapp
    chart: ./backendhelm
    installed: false

  - name: frontendapp
    chart: ./frontendhelm
    installed: false


